name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PYLINT_FLAGS: '--disable=C0114,C0115,C0116,E0401,R0903 --fail-under=9 --variable-rgx="[a-z_][a-z0-9_]{0,30}"'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Lint tools
      working-directory: ./tools
      run: |
        pylint ${{env.PYLINT_FLAGS}} `ls|grep .py$|xargs`
    - name: Lint solutions
      working-directory: ./solutions
      run: |
        pylint ${{env.PYLINT_FLAGS}} `ls|grep .py$|xargs`
